# Site settings
title: Analytics for Big and Complex Data
email: xi.rossi.luo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analytics for Big and Complex Data (ABCD) Group
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bigcomplexdata.com" # the base hostname & protocol for your site
## url: "http://127.0.0.1:4000"
twitter_username: xrluo
github_username:  rluo

# Build settings
markdown: kramdown
future: true

# These override Jekyll defaults
permalink: date

# These are new (in addition to Jekyll's elements above )
organization: ABCD Group
placeholderimagesbaseurl: http://placehold.it/

timezone: "America/New_York"
production: true

